ALTER TABLE public.peladas
  ADD COLUMN IF NOT EXISTS recorrente BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS dia_semana SMALLINT,
  ADD COLUMN IF NOT EXISTS antecedencia_dias_lista SMALLINT NOT NULL DEFAULT 3,
  ADD COLUMN IF NOT EXISTS recorrente_raiz_id UUID REFERENCES public.peladas(id) ON DELETE SET NULL;